apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ddmedistock
  namespace: ddmedistock
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "25m"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - app.ddmedistock.example
      secretName: ddmedistock-tls
  rules:
    - host: app.ddmedistock.example
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ddmedistock-app
                port:
                  number: 80
